ESTADOS_IDEA = {
    "ENVIADA": "ENVIADA",
    "EN PROCESO": "EN PROCESO",
    "APROBADA": "APROBADA",
    "RECHAZADA": "RECHAZADA",
    "FINALIZADA": "FINALIZADA",
    "BORRADOR": "BORRADOR"
}

ESTADOS_GESTOR = [
    ESTADOS_IDEA["ENVIADA"],
    ESTADOS_IDEA["EN PROCESO"],
    ESTADOS_IDEA["RECHAZADA"],
    ESTADOS_IDEA["APROBADA"],
    ESTADOS_IDEA["FINALIZADA"]
]

ESTADOS_GENERAL = [
    ESTADOS_IDEA["ENVIADA"],
    ESTADOS_IDEA["EN PROCESO"],
    ESTADOS_IDEA["BORRADOR"],
    ESTADOS_IDEA["APROBADA"],
    ESTADOS_IDEA["RECHAZADA"],
    ESTADOS_IDEA["FINALIZADA"]
]