ESTADOS_FEEDBACK = {
    "PENDIENTE": "PENDIENTE",
    "FINALIZADO": "FINALIZADO",
    "EN PROCESO": "EN PROCESO"
}

ESTADOS_GESTOR = [
    ESTADOS_FEEDBACK["PENDIENTE"],
    ESTADOS_FEEDBACK["FINALIZADO"],
    ESTADOS_FEEDBACK["EN PROCESO"]

]

ESTADOS_GENERAL = [
    ESTADOS_FEEDBACK["PENDIENTE"],
    ESTADOS_FEEDBACK["FINALIZADO"],
    ESTADOS_FEEDBACK["EN PROCESO"]
]