ESTADOS_FEEDBACK = {
    "PENDIENTE": "PENDIENTE",
    "FINALIZADA": "FINALIZADA",
}

ESTADOS_GESTOR = [
    ESTADOS_FEEDBACK["PENDIENTE"],
    ESTADOS_FEEDBACK["FINALIZADA"]
]

ESTADOS_GENERAL = [
    ESTADOS_FEEDBACK["PENDIENTE"],
    ESTADOS_FEEDBACK["FINALIZADA"]
]